VERSION 0.8

image:
    FROM --pass-args ../../+base-image

    # Install Go (download from official source to get latest version)
    # renovate: datasource=golang-version depName=golang
    ARG GO_VERSION=1.27.1
    ARG TARGETARCH
    RUN wget -q "https://go.dev/dl/go${GO_VERSION}.linux-${TARGETARCH}.tar.gz" && \
        tar -C /usr/local -xzf "go${GO_VERSION}.linux-${TARGETARCH}.tar.gz" && \
        rm "go${GO_VERSION}.linux-${TARGETARCH}.tar.gz"
    ENV PATH="/usr/local/go/bin:/root/go/bin:$PATH"

    # Install golangci-lint v2
    # renovate: datasource=github-releases depName=golangci/golangci-lint
    ARG GOLANGCI_LINT_VERSION=v2.13.2
    RUN curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | \
        sh -s -- -b /usr/local/bin ${GOLANGCI_LINT_VERSION}

    # Verify installations
    RUN go version && golangci-lint --version

    ARG VERSION=main
    SAVE IMAGE --push earthly/lunar-lib:golang-$VERSION
