#!/bin/bash
# ISO 3166-1 country names used for license text scanning.
# Excludes high-false-positive entries (common English words/names):
#   Georgia, Jordan, Chad, Mali, Tonga, Niger, Guinea, Monaco, Dominica

COUNTRY_NAMES=(
  "Afghanistan"
  "Albania"
  "Algeria"
  "Andorra"
  "Angola"
  "Antigua and Barbuda"
  "Argentina"
  "Armenia"
  "Australia"
  "Austria"
  "Azerbaijan"
  "Bahamas"
  "Bahrain"
  "Bangladesh"
  "Barbados"
  "Belarus"
  "Belgium"
  "Belize"
  "Benin"
  "Bhutan"
  "Bolivia"
  "Bosnia and Herzegovina"
  "Botswana"
  "Brazil"
  "Brunei"
  "Bulgaria"
  "Burkina Faso"
  "Burundi"
  "Cabo Verde"
  "Cambodia"
  "Cameroon"
  "Canada"
  "Central African Republic"
  "China"
  "Colombia"
  "Comoros"
  "Congo"
  "Costa Rica"
  "Croatia"
  "Cuba"
  "Cyprus"
  "Czech Republic"
  "Czechia"
  "Democratic Republic of the Congo"
  "Denmark"
  "Djibouti"
  "Dominican Republic"
  "East Timor"
  "Ecuador"
  "Egypt"
  "El Salvador"
  "Equatorial Guinea"
  "Eritrea"
  "Estonia"
  "Eswatini"
  "Ethiopia"
  "Fiji"
  "Finland"
  "France"
  "Gabon"
  "Gambia"
  "Germany"
  "Ghana"
  "Greece"
  "Grenada"
  "Guatemala"
  "Guyana"
  "Haiti"
  "Honduras"
  "Hungary"
  "Iceland"
  "India"
  "Indonesia"
  "Iran"
  "Iraq"
  "Ireland"
  "Israel"
  "Italy"
  "Ivory Coast"
  "Jamaica"
  "Japan"
  "Kazakhstan"
  "Kenya"
  "Kiribati"
  "Kosovo"
  "Kuwait"
  "Kyrgyzstan"
  "Laos"
  "Latvia"
  "Lebanon"
  "Lesotho"
  "Liberia"
  "Libya"
  "Liechtenstein"
  "Lithuania"
  "Luxembourg"
  "Madagascar"
  "Malawi"
  "Malaysia"
  "Maldives"
  "Malta"
  "Marshall Islands"
  "Mauritania"
  "Mauritius"
  "Mexico"
  "Micronesia"
  "Moldova"
  "Mongolia"
  "Montenegro"
  "Morocco"
  "Mozambique"
  "Myanmar"
  "Namibia"
  "Nauru"
  "Nepal"
  "Netherlands"
  "New Zealand"
  "Nicaragua"
  "Nigeria"
  "North Korea"
  "North Macedonia"
  "Norway"
  "Oman"
  "Pakistan"
  "Palau"
  "Palestine"
  "Panama"
  "Papua New Guinea"
  "Paraguay"
  "Peru"
  "Philippines"
  "Poland"
  "Portugal"
  "Qatar"
  "Romania"
  "Russia"
  "Rwanda"
  "Saint Kitts and Nevis"
  "Saint Lucia"
  "Saint Vincent and the Grenadines"
  "Samoa"
  "San Marino"
  "Sao Tome and Principe"
  "Saudi Arabia"
  "Senegal"
  "Serbia"
  "Seychelles"
  "Sierra Leone"
  "Singapore"
  "Slovakia"
  "Slovenia"
  "Solomon Islands"
  "Somalia"
  "South Africa"
  "South Korea"
  "South Sudan"
  "Spain"
  "Sri Lanka"
  "Sudan"
  "Suriname"
  "Sweden"
  "Switzerland"
  "Syria"
  "Taiwan"
  "Tajikistan"
  "Tanzania"
  "Thailand"
  "Togo"
  "Trinidad and Tobago"
  "Tunisia"
  "Turkey"
  "Turkmenistan"
  "Tuvalu"
  "Uganda"
  "Ukraine"
  "United Arab Emirates"
  "United Kingdom"
  "United States"
  "Uruguay"
  "Uzbekistan"
  "Vanuatu"
  "Vatican City"
  "Venezuela"
  "Vietnam"
  "Yemen"
  "Zambia"
  "Zimbabwe"

  # Common alternate names for high-interest countries
  # Short codes (PRC, ROC, EU, UAE, etc.) omitted — too many false positives
  "Russian Federation"
  "People's Republic of China"
  "Republic of China"
  "Republic of Korea"
  "Hong Kong"
  "Macau"
  "Soviet Union"
  "Great Britain"
  "England"
  "Scotland"
  "Wales"
  "Northern Ireland"
  "Deutschland"
  "Bundesrepublik"
  "Schweiz"
  "Suisse"
  "Svizzera"
  "Nederland"
)
