VERSION 0.8
# Build the istio collector image
image:
    FROM --pass-args ../../+base-image

    # Install istioctl for offline Istio config validation (istioctl analyze).
    ARG TARGETARCH
    ARG ISTIO_VERSION=1.22.0
    RUN ARCH=$(echo "${TARGETARCH}" | sed 's/amd64/amd64/; s/arm64/arm64/') && \
        curl -sSL "https://github.com/istio/istio/releases/download/${ISTIO_VERSION}/istioctl-${ISTIO_VERSION}-linux-${ARCH}.tar.gz" | tar xz && \
        mv istioctl /usr/local/bin/ && \
        chmod +x /usr/local/bin/istioctl

    ARG VERSION=main
    SAVE IMAGE --push earthly/lunar-lib:istio-$VERSION
